package org.openmrs.performance;

public class Constants {
	public static final String BASE_URL = "http://localhost";
	public static final String ENV_SIMULATION_PRESET = "SIMULATION_PRESET";
	public static final String ENV_USER_INCREMENT_PER_TIER = "USER_INCREMENT_PER_TIER";
	public static final String ENV_TIER_DURATION = "TIER_DURATION_MINUTES";
	public static final String ENV_TIER_COUNT = "TIER_COUNT";
	
	public static final String OUTPATIENT_CLINIC_LOCATION_UUID = "44c3efb0-2583-4c80-a79e-1f756a03c0a1";
	public static final String FACULTY_VISIT_TYPE_UUID = "7b0f5697-27e3-40c4-8bae-f4049abfb4ed";
	
	public static final String CARE_SETTING_UUID = "6f0c9a92-6f24-11e3-af88-005056821db0";
	public static final String DRUG_ORDER = "131168f4-15f5-102d-96e4-000c29c2a5d7";
	
	// Observation Types
	public static final String SYSTOLIC_BLOOD_PRESSURE = "5085AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String DIASTOLIC_BLOOD_PRESSURE = "5086AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String TEMPERATURE_C = "5088AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String HEIGHT_CM = "5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String WEIGHT_KG = "5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String PULSE = "5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String MID_UPPER_ARM_CIRCUMFERENCE = "1343AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String RESPIRATORY_RATE = "5242AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String ARTERIAL_BLOOD_OXYGEN_SATURATION = "5092AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String UNKNOWN_OBSERVATION_TYPE = "165095AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PERSON_ATTRIBUTE_PHONE_NUMBER = "14d4f066-15f5-102d-96e4-000c29c2a5d7";
	
	public static final String TABLET = "1513AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String ORAL = "160240AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String ONCE_DAILY = "136ebdb7-e989-47cf-8ec2-4e8b2ffe0ab3";
	public static final String DAYS = "1072AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String ORDER = "39da3525-afe4-45ff-8977-c53b7b359158";
	
	public static final String DEFAULT_DOSING_TYPE = "org.openmrs.SimpleDosingInstructions";

	// Allergies
	public static final String DRUG_ALLERGEN_UUID = "162555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final String ENVIRONMENTAL_ALLERGEN_UUID = "162552AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final	String FOOD_ALLERGEN_UUID = "162554AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final	String ALLERGY_REACTION_UUID = "162553AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final	String CODED_ALLERGEN_UUID = "71617AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	public static final	String SEVERITY_UUID = "1498AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
}
