name: Validate code formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatter-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Run code Formatter Validate
        run: ./mvnw formatter:validate
