name: Validate code formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatter-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Run code Formatter Validate
        run: ./mvnw formatter:validate
